/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
  'index',
  'download',
    {
      type: 'category',
      label: 'API',
      collapsible: true,
      collapsed: false,
      items: ['tkg-integration/sdk-prepare',
        {
          type: 'category',
          label: 'Basic Integration',
          
          items: ['tkg-integration/sdk-basic/sdk-import','tkg-integration/sdk-basic/sdk-config', 'tkg-integration/sdk-basic/sdk-func-init','tkg-integration/sdk-basic/sdk-func-privacy','tkg-integration/sdk-basic/sdk-func-ads','tkg-integration/sdk-basic/sdk-func-event']
          
        },
        'tkg-integration/sdk-other-func', 
         {
          type: 'category',
          label: 'Build Package',
          items: ['tkg-integration/sdk-projectsettings/sdk-projectsettings-android', 'tkg-integration/sdk-projectsettings/sdk-projectsettings-ios']
          
        },
         {
          type: 'category',
          label: 'Integration Verification',
          items: ['tkg-integration/sdk-test/sdk-test-android', 'tkg-integration/sdk-test/sdk-test-iOS']
          
        },
        'tkg-integration/sdk-package',
      ]
    },

  'faq'
  ]
   ,
  "apiSidebar": [
    "api/common-api",
    'api/advance-api'
  ]


   // docs: [
   //  'introduction',
   //  {
   //    type: 'category',
   //    label: '入门',
   //    collapsed: false,
   //    items: ['download', 'faq', 'index'],
   //  }
   //  ]
};

module.exports = sidebars;
